#include QMK_KEYBOARD_H

#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(0x7c73, KC_Q, KC_W, KC_E, KC_R, KC_T, LT(3,KC_ESC), MT(MOD_LGUI,KC_A), MT(MOD_LALT,KC_S), MT(MOD_LSFT,KC_D), MT(MOD_LCTL,KC_F), KC_G, KC_TRNS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, LT(1,KC_SPC), KC_BSLS, KC_P, KC_O, KC_I, KC_U, KC_Y, LT(4,KC_QUOT), MT(MOD_LGUI | MOD_RGUI,KC_SCLN), MT(MOD_LALT | MOD_RALT,KC_L), MT(MOD_LSFT | MOD_RSFT,KC_K), MT(MOD_LCTL | MOD_RCTL,KC_J), KC_H, C(G(KC_Q)), KC_SLSH, KC_DOT, KC_COMM, KC_M, KC_N, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, LT(2,KC_ENT)),

[_LAYER1] = LAYOUT(KC_TRNS, KC_TRNS, S(KC_7), S(KC_8), KC_TRNS, KC_PMNS, KC_TRNS, KC_TRNS, S(KC_4), S(KC_5), S(KC_6), KC_PPLS, KC_TRNS, KC_TRNS, S(KC_1), S(KC_2), S(KC_3), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MACRO(1), KC_EQL, S(KC_RBRC), S(KC_LBRC), S(KC_MINS), KC_GRV, MACRO(0), S(KC_EQL), KC_RBRC, KC_LBRC, KC_MINS, KC_TRNS, S(KC_GRV), S(KC_DOT), S(KC_0), S(KC_9), S(KC_COMM), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER2] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET, KC_TRNS, C(KC_TAB), KC_TRNS, KC_TRNS, C(S(KC_TAB)), KC_TRNS, KC_TRNS, KC_RGHT, KC_UP, KC_DOWN, KC_LEFT, KC_TRNS, KC_TRNS, KC_END, KC_PGUP, KC_PGDN, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER3] = LAYOUT(RM_TOGG, KC_TRNS, KC_TRNS, KC_TRNS, RGB_VAD, RGB_VAI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MSTP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, KC_VOLU, KC_VOLD, KC_MPRV, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_MPLY),

[_LAYER4] = LAYOUT(KC_NLCK, KC_TRNS, KC_7, KC_8, KC_9, KC_TRNS, KC_TRNS, KC_TRNS, KC_4, KC_5, KC_6, KC_TRNS, KC_TRNS, KC_0, KC_1, KC_2, KC_3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_TRNS, KC_TRNS, KC_F10, KC_F1, KC_F2, KC_F3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)

};
